### ISSUE TITLE
[Question]: 이 라이브러리를 언제 사용해야 유용한지 궁금합니다.

### ISSUE THREAD

**Issue by algoORgoal** [nayounsang/relation-map#25]
## Question

Map object의 method `Map.get()`을 사용했을 때는 time complexity가 O(1)에 근접한 것으로 알고 있습니다. 따라서 퍼포먼스 밴치마킹에서`BiMap()`과 큰 속도 차이를 보이지 않습니다. readme.md에 있는 예제에서 map을 접근할 때 발생하는 bottleneck은 `map.values()` 통해 **Map object를 배열로 변환하고, 이를 순회하는 과정에서 온다고 봅니다.**

- 소스코드 변경

```javascript
import { BiMap } from "relation-map";

const biMap = new BiMap();
const map = new Map();
const N = 12345;
for (let i = 0; i < N; i++) {
  map.set(String(i), i);
  biMap.set(String(i), i);
}
const mapTime = { total: 0, average: 0 };
const biMapTime = { total: 0, average: 0 };

const start1 = performance.now();
for (let i = 0; i < N; i++) {
  // Instead of linear search, the v8 engine manages a hash table internally, leading to (almost) constant time complexity for lookup.
  map.get(i);
}
const end1 = performance.now();
mapTime.total = end1 - start1;
mapTime.average = (end1 - start1) / N;

const start2 = performance.now();
for (let i = 0; i < N; i++) {
  // Find with O(1) complexity.
  biMap.getByRight(i);
}
const end2 = performance.now();
biMapTime.total = end2 - start2;
biMapTime.average = (end2 - start2) / N;
console.log({ mapTime });
console.log({ biMapTime });
```

- 실행 결과
![execution result on terminal](https://github.com/user-attachments/assets/d415ce4a-0a0e-4be6-bb1c-14fc5a1dceac)

- Reproduction link
https://codesandbox.io/p/devbox/naughty-clarke-forked-pxqm77?file=%2Findex.js%3A1%2C1-32%2C1&workspaceId=ws_L3CS8wVk4ZoX3wkBnrcLHu

## Additional Information

- [Map의 시간복잡도에 대한 stackoverflow의 답변](https://stackoverflow.com/questions/33611509/es6-map-and-set-complexity-v8-implementation)

> Is it a fair assumption that in v8 implementation retrieval / lookup is O(1)?
> Yes. V8 uses a variant of hash tables that generally have O(1) complexity for these operations.

**Comment by nayounsang** [comment]
해당 자료구조는 1대1 매칭 관계를 보장해줍니다.
Map을 예로 들자면 중복되는 value가 없고, 중복되는 key가 없으며 key와 value는 1대1 매칭 관계를 같습니다.
docs에 제시된 케이스는 BiMap이 아니고선 1대1관계르 보장하기 위한 O(N)의 연산을 수행해 오버헤드가 발생합니다.
단순한 get은 BiMap과 map모두 O(1)이므로 차이가 거의 존재하지 않습니다.
이 프로젝트에 대한 관심 사랑합니다! ❤️
